export const NEW_POST = 'NEW_POST';
export const ENTER_TEXT = 'ENTER_TEXT';
export const SAVE_POST_FAILURE = 'SAVE_POST_FAILURE';
export const SAVE_POST_REQUEST = 'SAVE_POST_REQUEST';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';